create table if not exists public.event_programs (
  event_id uuid primary key references public.events(id) on delete cascade,
  config jsonb not null default '{"version":1,"rounds_target":7,"blocks":[]}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists public.event_runtime (
  event_id uuid primary key references public.events(id) on delete cascade,
  run_status text not null default 'idle' check (run_status in ('idle','running','paused','finished')),
  current_block_id text not null default 'arrival',
  current_block_index integer not null default 0 check (current_block_index >= 0),
  current_round integer not null default 0 check (current_round >= 0),
  current_round_id uuid,
  current_movie_id uuid references public.movie_candidates(id) on delete set null,
  current_question jsonb,
  vote_state text not null default 'closed' check (vote_state in ('closed','open')),
  results_visible boolean not null default false,
  video_state jsonb not null default '{"status":"idle"}'::jsonb,
  revision bigint not null default 0,
  started_at timestamptz,
  block_started_at timestamptz,
  paused_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.event_rounds (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  round_no integer not null check (round_no > 0),
  block_id text not null,
  status text not null default 'draft' check (status in ('draft','active','closed','skipped')),
  movie_candidate_id uuid references public.movie_candidates(id) on delete set null,
  question jsonb,
  vote_state text not null default 'closed' check (vote_state in ('closed','open')),
  results_visible boolean not null default false,
  video_state jsonb not null default '{"status":"idle"}'::jsonb,
  started_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(event_id,round_no)
);

alter table public.event_runtime
  drop constraint if exists event_runtime_current_round_id_fkey;
alter table public.event_runtime
  add constraint event_runtime_current_round_id_fkey
  foreign key (current_round_id) references public.event_rounds(id) on delete set null;

create table if not exists public.event_votes (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null references public.events(id) on delete cascade,
  round_id uuid not null references public.event_rounds(id) on delete cascade,
  question_key text not null,
  user_id uuid not null references public.users(id) on delete cascade,
  answer jsonb not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(round_id,question_key,user_id)
);

create table if not exists public.event_runtime_log (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.events(id) on delete cascade,
  action text not null,
  actor_user_id uuid references public.users(id) on delete set null,
  from_state jsonb not null default '{}'::jsonb,
  to_state jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.event_presence (
  event_id uuid not null references public.events(id) on delete cascade,
  user_id uuid not null references public.users(id) on delete cascade,
  last_seen_at timestamptz not null default now(),
  primary key(event_id,user_id)
);

alter table public.movie_candidates
  add column if not exists enabled_for_event boolean not null default true,
  add column if not exists genre text,
  add column if not exists country text,
  add column if not exists trailer_status text not null default 'unchecked',
  add column if not exists clip_status text not null default 'unchecked',
  add column if not exists source_type text,
  add column if not exists source_platform text,
  add column if not exists source_url text,
  add column if not exists video_id text,
  add column if not exists start_sec integer,
  add column if not exists end_sec integer,
  add column if not exists source_channel text,
  add column if not exists source_verified boolean not null default false,
  add column if not exists verified_at timestamptz,
  add column if not exists usage_status text not null default 'needs_review',
  add column if not exists discussion_prompts jsonb not null default '[]'::jsonb,
  add column if not exists animal_comment text,
  add column if not exists tags text[] not null default '{}'::text[];

alter table public.crumb_ledger
  add column if not exists event_id uuid references public.events(id) on delete set null,
  add column if not exists source_id text;

create index if not exists event_rounds_event_created_idx
  on public.event_rounds(event_id,created_at desc);
create index if not exists event_votes_round_idx
  on public.event_votes(round_id,question_key);
create index if not exists event_votes_event_created_idx
  on public.event_votes(event_id,created_at desc);
create index if not exists event_runtime_log_event_idx
  on public.event_runtime_log(event_id,created_at desc);
create index if not exists event_presence_seen_idx
  on public.event_presence(event_id,last_seen_at desc);
create index if not exists movie_candidates_event_ready_idx
  on public.movie_candidates(event_id,enabled_for_event,usage_status);

alter table public.event_programs enable row level security;
alter table public.event_runtime enable row level security;
alter table public.event_rounds enable row level security;
alter table public.event_votes enable row level security;
alter table public.event_runtime_log enable row level security;
alter table public.event_presence enable row level security;

revoke all on public.event_programs from anon, authenticated, public;
revoke all on public.event_runtime from anon, authenticated, public;
revoke all on public.event_rounds from anon, authenticated, public;
revoke all on public.event_votes from anon, authenticated, public;
revoke all on public.event_runtime_log from anon, authenticated, public;
revoke all on public.event_presence from anon, authenticated, public;

grant select,insert,update,delete on public.event_programs to service_role;
grant select,insert,update,delete on public.event_runtime to service_role;
grant select,insert,update,delete on public.event_rounds to service_role;
grant select,insert,update,delete on public.event_votes to service_role;
grant select,insert,update,delete on public.event_runtime_log to service_role;
grant select,insert,update,delete on public.event_presence to service_role;
grant usage,select on sequence public.event_runtime_log_id_seq to service_role;

insert into public.event_programs(event_id,config)
select e.id,
jsonb_build_object(
  'version',1,
  'rounds_target',7,
  'blocks',jsonb_build_array(
    jsonb_build_object('id','arrival','type','arrival','title','сбор гостей','duration_min',15,'enabled',true),
    jsonb_build_object('id','onboarding','type','onboarding','title','знакомство с животиной','duration_min',5,'enabled',true),
    jsonb_build_object('id','warm_up','type','warm_up','title','первый общий интерактив','duration_min',5,'enabled',true),
    jsonb_build_object('id','cinema_rounds_part_1','type','cinema_rounds','title','первый киношный блок','duration_min',40,'rounds_target',3,'enabled',true),
    jsonb_build_object('id','music_live','type','music_live','title','живое музыкальное выступление','duration_min',30,'enabled',true),
    jsonb_build_object('id','cinema_rounds_part_2','type','cinema_rounds','title','второй киношный блок','duration_min',45,'rounds_target',4,'enabled',true),
    jsonb_build_object('id','final_vote','type','final_vote','title','финальный выбор','duration_min',5,'enabled',true),
    jsonb_build_object('id','finale','type','finale','title','итог вечера','duration_min',5,'enabled',true),
    jsonb_build_object('id','post_event','type','post_event','title','после события','duration_min',0,'enabled',true)
  )
)
from public.events e
on conflict(event_id) do nothing;

insert into public.event_runtime(event_id,current_block_id,current_block_index)
select e.id,'arrival',0 from public.events e
on conflict(event_id) do nothing;
